version: 2.1

executors:
  meson_ubuntu_builder:
    docker:
      - image: squidfarts/ubuntu-sys:dev-deps

  meson_debain_builder:
    docker:
      - image: squidfarts/debian-sys:dev-deps

  meson_fedora_builder:
    docker:
      - image: squidfarts/fedora-sys:dev-deps


jobs:
  meson_ubuntu_build:
    executor: meson_ubuntu_builder
    steps:
      - checkout
      - run: pip3 install PyQt5 --user
      - run: pip3 install pytest --user
      - run: pip3 install pytest-qt --user
      - run: python3 tool/testrun.py
      
  meson_debain_build:
    executor: meson_debain_builder
    steps:
      - checkout
      - run: pip3 install PyQt5 --user
      - run: pip3 install pytest --user
      - run: pip3 install pytest-qt --user
      - run: python3 tool/testrun.py

  meson_fedora_build:
    executor: meson_fedora_builder
    steps:
      - checkout
      - run: pip3 install PyQt5 --user
      - run: pip3 install pytest --user
      - run: pip3 install pytest-qt --user
      - run: python3 tool/testrun.py


workflows:
  version: 2
  workflow:
    jobs:
      - meson_ubuntu_build
      - meson_debain_build
      - meson_fedora_build