version: 2.1
executors:
  mesonui_builder:
    docker:
      - image: squidfarts/mesonui-deps:0.1.0

jobs:
  mesonui_build:
    executor: mesonui_builder
    steps:
      - checkout
      - run: python3 tool/testrun.py

workflows:
  version: 2
  workflow:
    jobs:
      - mesonui_build