version: 2.1
executors:
  mesonui_builder:
    docker:
      - image: squidfarts/mesonui-deps:0.1.1

jobs:
  mesonui_build:
    executor: mesonui_builder
    steps:
      - checkout
      - run: pytest run_utests.py
      #  - run: pytest run_uitests.py

workflows:
  version: 2
  workflow:
    jobs:
      - mesonui_build